C:\VulkanSDK\1.3.283.0\Bin\glslc.exe simple.frag -o simpleFrag.spv
C:\VulkanSDK\1.3.283.0\Bin\glslc.exe simple.vert -o simpleVert.spv
C:\VulkanSDK\1.3.283.0\Bin\glslc.exe BlinnShader.frag -o BlinnFrag.spv
C:\VulkanSDK\1.3.283.0\Bin\glslc.exe BlinnShader.vert -o BlinnVert.spv
C:\VulkanSDK\1.3.283.0\Bin\glslc.exe EmissionShader.frag -o EmissionFrag.spv
C:\VulkanSDK\1.3.283.0\Bin\glslc.exe EmissionShader.vert -o EmissionVert.spv
C:\VulkanSDK\1.3.283.0\Bin\glslc.exe NormalMapShader.frag -o NormalMapFrag.spv
C:\VulkanSDK\1.3.283.0\Bin\glslc.exe NormalMapShader.vert -o NormalMapVert.spv
C:\VulkanSDK\1.3.283.0\Bin\glslc.exe SkyBoxShader.frag -o SkyBoxFrag.spv
C:\VulkanSDK\1.3.283.0\Bin\glslc.exe SkyBoxShader.vert -o SkyBoxVert.spv
C:\VulkanSDK\1.3.283.0\Bin\glslc.exe TextShader.frag -o TextFrag.spv
C:\VulkanSDK\1.3.283.0\Bin\glslc.exe TextShader.vert -o TextVert.spv